databases:
  - name: homey
    databaseName: homey
    user: homey_api2

services:
  - type: web
    name: homey_api2
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: homey_api2
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
