databases:
  - name: postgres
    databaseName: Mydatabase
    user: moringa

services:
  - type: web
    name: moringa
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moringa
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
